issues:
  exclude-rules:
    # Disable some linters in tests.
    - path: _test\.go
      linters:
        - gochecknoglobals
        - funlen
    # Disable some linters in examples.
    - path: example/.*\.go
      linters:
        - forbidigo

linters:
  enable:
    - goimports
    - unconvert
    - misspell
    - gocyclo
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - gocritic
    - gochecknoinits

