issues:
  exclude-rules:
    # Disable some linters in tests.
    - path: _test\.go
      linters:
        - gochecknoglobals
        - funlen
    # Disable some linters in examples.
    - path: example/.*\.go
      linters:
        - forbidigo

linters:
  enable:
    - testpackage
    - exportloopref
  disable:
    - paralleltest
    - gofumpt
    - exhaustivestruct
    - scopelint
  presets:
    - bugs
    - complexity
    - format
    - performance
    - style
    - unused
