name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-12]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21

    - name: Test
      run: make test

  lint:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2

    - name: Lint
      uses: golangci/golangci-lint-action@v3.7.0
      with:
        args: "-v"
        version: v1.55.2
